---
# tasks file for pandorafms_server

# manual install is required due to the pandorafms_server package's broken dependencies.

- name: install required packages
  import_tasks: install-required-packages.yml

- name: check pandorafms_server is installed
  shell: 'rpm -q {{ pandorafms_server_package_name }}'
  register: pandorafms_server_package_installed
  failed_when: false
  changed_when: false

- shell: 'rpm -{{ i_or_F }} --nodeps $(yumdownloader -q --urls {{ pandorafms_server_package }})'
  register: rpm_result
  vars:
    i_or_F: '{% if pandorafms_server_package_installed.rc != 0 %}"i"{% else %}"F"{% endif %}'
  changed_when:
    - 'rpm_result is success'
    - '"package {{ pandorafms_server_package_name }} is not installed" in rpm_result.stdout_lines'
  when: >
    pandorafms_server_package_installed.rc != 0
      or pandorafms_server_package_name not in pandorafms_server_package_installed.stdout_lines

